### PR TITLE
Add onended for audio element

### PR DESCRIPTION
**Pull request by modulesio**
Continuation of #567.

### CODE REVIEW

**Comment by machenmusik** [comment]
LGTM, if it still works after the `suspend-resume` rebase...

**Comment by modulesio** [comment]
- [ ] Should add a test for it in an audio example

**Comment by modulesio** [comment]
The [newly added example](https://github.com/webmixedreality/exokit/pull/568/files#diff-be3eaa002fac063a7345497bbaf2f239R104) seems to fire correctly.

**Comment by modulesio** [comment]
Tested both Windows and Magic Leap.

**Pull request merged**
