### PR TITLE
Use > as the REPL prompt for compatibility

### PR DESCRIPTION
**Pull request by shawwn**

### CODE REVIEW

**Comment by shawwn** [comment]
One reason to do this is because IDEs are set up to easily integrate with REPLs that use > as the prompt.

(E.g. emacs)

**Comment by modulesio** [comment]
Interesting... can we flag it?

**Comment by shawwn** [comment]
Let's just use > as the prompt. No need to add another flag

**Comment by modulesio** [comment]
I kind of like the flair of having it as is :P.

I don't think emacs should be dictating the prompt format; there is not really a prompt standard to follow here.

**Comment by shawwn** [comment]
Up to you, but my point was that a lot of code has been written for the case of "Spawn a child process and wait for `> `"

Not just emacs, but pretty much any code that controls a REPL interactively via child process.

**Comment by shawwn** [comment]
Emojis win the day.

**Pull request closed without merging**
