### PR TITLE
move source code files into src, metadata/scripts dirs

### PR DESCRIPTION
**Pull request by ngokevin**
The root project directory has 50 files and folders, makes it difficult to go through what's source code and what's other stuff (build configs, scripts, app manifests, deps). Proposing to move into src directory:

- Move index.js, core.js, native-bindings.js, bugsnag.js into src directory.

### CODE REVIEW

**Comment by modulesio** [comment]
I agree. There's a bigger win to moving the scripts, configs, and manifests up since they're the bulk of that 50.

https://github.com/webmixedreality/exokit/issues/431

**Comment by ngokevin** [comment]
That'd be nice too. I think those files above still belong in `src` since they're Exokit-specific source.

**Comment by ngokevin** [comment]
Updated/rebased with the metadata/scripts directories.

**Comment by modulesio** [comment]
What is [`tags`](https://github.com/webmixedreality/exokit/pull/430/files#diff-d57ac45256849d9b13e2422d91580fb9)?

**Comment by ngokevin** [comment]
Whoops, was my ctags file.

**Comment by ngokevin** [comment]
Yeah, I'll keep going with the CI, inevitable mistakes.

**Comment by ngokevin** [comment]
CI passes at least. Build scripts if any discrepancies you can probably catch quickly.

**Comment by modulesio** [comment]
Thanks, I forked this to https://github.com/webmixedreality/exokit/pull/459 for additional CI fixes.

**Pull request closed without merging**
