### PR TITLE
Add top-level `await` for the REPL

### PR DESCRIPTION
**Pull request by shawwn**
```
[x] _sleep = async ms => new Promise(accept => { setTimeout(() => { accept(); }, ms); })
[AsyncFunction: _sleep]
[x] await _sleep(1000); console.log('hi'); await _sleep(1000); console.log('there');
hi
there
undefined
[x] 
```

### CODE REVIEW

**Comment by modulesio** [comment]
I'm on board philsophically, but [`process-top-level-await` seems a gigantic library](https://github.com/shawwn/process-top-level-await)...

**Comment by shawwn** [comment]
You can see how it was generated here: https://github.com/shawwn/process-top-level-await/blob/98a1e1f2f726f485c7e834c27a3f435ba099993d/build.sh#L4-L8

I could forego the browserification and just export node's internal deps.

**Comment by modulesio** [comment]
Doesn't that add a whole new dependency that we need to rebuild when changing the Node environment?

**Comment by shawwn** [comment]
Nah, that's why I browserified it. It's completely self-contained.

**Comment by modulesio** [comment]
So when node adds new APIs it will show up magically?

**Comment by shawwn** [comment]
Yes. See https://github.com/nodejs/node/blob/a196aa2e24ef7069289fa4a9aa8c6862d82e6b5f/lib/internal/repl/await.js#L66 

Basically, it uses [acorn](https://www.npmjs.com/package/acorn) to parse the JS, looking for `await ...` expressions. If it finds any, it transforms the code into an equivalent `(async () => { .... })()` block. Otherwise it returns null.

**Comment by modulesio** [comment]
Why not just wrap `async` always? I don't understand the need for acorn in that case.

**Comment by shawwn** [comment]
It's difficult to wrap an arbitrary REPL input without acorn.

Consider how you'd transform this:

```
await _sleep(1000); console.log('hello'); await _sleep(1000); 42
```

into this:

```
(async () => {
  await _sleep(1000);
  console.log('hello');
  await _sleep(1000);
  return 42;
})();
```

(Notice the `return`.)

**Comment by modulesio** [comment]
Makes sense. I'm uncomfortable with the volume of code added to make this work though; it seems like there could be corner cases, as well as incorrect/confusing stack traces with such rewriting. The complexity seems out of proportion to the benefit.

I feel like this would be better off as a Node feature than an Exokit engine feature.

**Pull request closed without merging**
