### PR TITLE
Add BUILDING.md

### PR DESCRIPTION
**Pull request by modulesio**

### CODE REVIEW

**Comment by shawwn** [comment]
I think on Windows you need to install windows-build-tools.

**Comment by shawwn** [comment]
To be more precise, you can avoid installing Visual Studio by installing [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools) instead.

> Start PowerShell as Administrator and run: 

```
npm install --global --production windows-build-tools
```

Is there some reason that the full Visual Studio is required?

**Comment by modulesio** [comment]
> Is there some reason that the full Visual Studio is required?

No, but that is afaik exactly what `windows-build-tools` installs, just the CLI part.

**Comment by shawwn** [comment]
It installs Visual C++ Build Tools, which isn't the same thing as Visual Studio. In particular, Visual Studio ships with several CLI parts related to e.g. .NET and C# which aren't present in Visual C++ Build Tools.

**Comment by modulesio** [comment]
I don't think I've ever needed `--production`

**Comment by shawwn** [comment]
Still, it's in conflict with the [official instructions](https://github.com/felixrieseberg/windows-build-tools#readme). Unless there's a good reason to deviate from them, it's probably best to stick with the official installation method.

**Pull request merged**
