### PR TITLE
Add Discord webhook to travis.yml

### PR DESCRIPTION
**Pull request by chrisplatorres**
Uses script from https://github.com/webmixedreality/travis-ci-discord-webhook -- will need to add WEBHOOK_URL env variable in travis settings.

### CODE REVIEW

**Comment by modulesio** [comment]
The `WEBHOOK_URL` should be added.

**Comment by chrisplatorres** [comment]
It is added as an ENV_VARIABLE in travis settings, it is a webhook to the Discord channel so it shouldn't be public.

**Comment by modulesio** [comment]
Thanks, I think that's what we've got:

image

**Comment by chrisplatorres** [comment]
Merging to test.

**Pull request merged**
