### PR TITLE
Add missing gl.getUniform method

### PR DESCRIPTION
**Pull request by shawwn**
This fixes http://stack.gl/gl-shader/

### CODE REVIEW

**Comment by modulesio** [comment]
Ok so this looks good, but our getUniform implementation does not: it assumes array-y data type for the uniform. Per the mdn spec (https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getUniform), shouldn’t we be returning different type based on the internal type of the uniform by calling eg https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetActiveUniform.xhtml?

**Comment by modulesio** [comment]
Basically this PR looks good but it seems to reveal a deeper conformance bug. Do we want to merge and open an issue for the conformance or just fix it in one swoop here?

**Comment by shawwn** [comment]
Yeah, good point. I'm not sure whether it's best to merge this or to leave it out until the full solution is implemented.

**Comment by modulesio** [comment]
Thanks for the extra work!

**Pull request merged**
