### PR TITLE
Toggle bugsnag with NO_BUGSNAG=1

### PR DESCRIPTION
**Pull request by shawwn**

### CODE REVIEW

**Comment by modulesio** [comment]
I'm not sure if this should be encouraged... if there is a problem with bugsnag itself that should probably be fixed.

**Comment by shawwn** [comment]
Being able to turn off telemetry is usually a good idea. Especially when that telemetry is broken.

**Comment by modulesio** [comment]
To be fair, would we argue to fix tests by deleting them? The time we would want telemetry the most seems when there is a break.

**Comment by shawwn** [comment]
It was quite amazing to see the call trace, all the way down to OpenVR.

**Pull request closed without merging**
